<?php

namespace app\modules\admin\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "product".
 *
 * @property int $id
 * @property int $category_id
 * @property string $title
 * @property string $content
 * @property string|null $keywords
 * @property string|null $description
 * @property string $img
 */
class Product extends \yii\db\ActiveRecord
{
    public $file;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'product';
    }

    public function getCategory()
    {
        return $this->hasOne(Category::class, ['id' => 'category_id']);
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['category_id', 'title', 'content'], 'required'],
            [['category_id'], 'integer'],
            [['title', 'content', 'keywords', 'description', 'img'], 'string', 'max' => 255],
            [['file'], 'image'],

        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'category_id' => 'Категория',
            'title' => 'Наименование',
            'content' => 'Назначение',
            'keywords' => 'Ключевики',
            'description' => 'Описание',
            'img' => 'Фото',
            'file' => 'Фото',
            'category' => 'Категория выключателя',
        ];
    }

    public function beforeSave($insert)
    {
        if ($file = UploadedFile::getInstance($this, 'file')) {
            $dir = 'images/';
        }
        $file_name = uniqid() . '_' . $file->baseName . '.' . $file->extension;
        $this->img = $dir . $file_name;
        $file->saveAs($this->img);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
